routeNames = {"route_id": "route_long_name", 
              "100": "Primo Fredericksburg Road", 
              "102": "Primo Military", 
              "103": "Primo Zarzamora", 
              "14": "Perrin Beitel Skip", 
              "17": "IH-35 Express", 
              "2": "Blanco Frequent", 
              "20": "New Braunfels Frequent", 
              "202": "Blanco Road 2 Lineup", 
              "204": "San Pedro / McCullough 4-5 Lineup", 
              "209": "Broadway 9 Lineup", 
              "21": "Kirby / Converse", 
              "214": "Austin Hwy / Randolph 14-17 Lineup", 
              "22": "Hays", 
              "222": "Hays / E Houston 22-24 Lineup", 
              "225": "E Commerce / MLK 25-26 Lineup", 
              "230": "Rigsby / Porter 30-28 Lineup", 
              "232": "Steves / S St Marys 32-34 Lineup", 
              "24": "East Houston", 
              "242": "Roosevelt / S Presa 42-36 Lineup", 
              "243": "S Flores / Pleasanton 43-44 Lineup",
              "246": "Commercial 46 Lineup", 
              "25": "East Commerce Frequent", 
              "251": "Nogalitos / Kirk 51-62 Lineup", 
              "26": "Martin Luther King", 
              "268": "Guadalupe / Ceralvo 68-66 Lineup", 
              "275": "Commerce / Laredo 75-67 Lineup", 
              "276": "Commerce / Kel-Lac TC 76-64 Lineup", 
              "277": "Martin / Ruiz 77-79 Lineup", 
              "28": "Porter Frequent", 
              "282": "Culebra 82 Lineup", 
              "288": "Bandera / Evers 88 Lineup", 
              "289": "Poplar / Woodlawn 89-90 Lineup", 
              "296": "Vance Jcksn / West Ave 96-97 Lineup", 
              "3": "San Pedro Skip", "30": "Rigsby", 
              "32": "Steves", 
              "34": "South St Marys Frequent", 
              "36": "South Presa", 
              "4": "San Pedro Frequent", 
              "42": "Roosevelt", 
              "43": "South Flores", 
              "44": "Pleasanton", 
              "46": "Commercial", 
              "5": "McCullough", 
              "501": "UTSA / Leon Valley", 
              "502": "Thousand Oaks", 
              "503": "Huebner Crosstown", 
              "505": "Basse", 
              "509": "Hildebrand", 
              "51": "Nogalitos", 
              "515": "Southcross", 
              "522": "Babcock", 
              "524": "General McMullen Frequent", 
              "534": "Wurzbach Frequent", 
              "552": "Loop 410 / W. W. White Skip", 
              "602": "North Star / Medical Center", 
              "603": "Medical Center / UTSA", 
              "604": "Medical Center / University Heights", 
              "607": "Medical Center / Ingram", 
              "609": "Ingram / Mainland / Medical Center", 
              "610": "Ingram / Northwest Crossing", 
              "611": "Valley-Hi / Kel-Lac", 
              "612": "Kel-Lac / Westlakes", 
              "613": "Heritage NW / Kel-Lac", 
              "614": "Hidden Cove / Kel-Lac", 
              "615": "Kel-Lac / Heritage Park", 
              "616": "Sky Harbour / Kel-Lac", 
              "617": "Kel-Lac / Rainbow Hills", 
              "618": "Ingram / Westlakes", 
              "619": "Kel-Lac / Indian Creek", 
              "62": "Kirk", 
              "620": "Northwest Vista College / Ingram", 
              "632": "Randolph / Ventura", 
              "64": "US 90 Express", 
              "647": "North Star / Harry Wurzbach", 
              "648": "North Star / Stone Oak", 
              "651": "Deco District / Castle Hills", 
              "66": "Ceralvo", "67": "Laredo", 
              "68": "Guadalupe Frequent", 
              "7": "US 281 Stone Oak / Brooks Express", 
              "75": "West Commerce Frequent", 
              "76": "West Commerce Skip", 
              "77": "Martin", 
              "79": "Ruiz", 
              "8": "North St Marys", 
              "82": "Culebra Frequent", 
              "88": "Bandera Frequent", 
              "89": "Poplar", 
              "9": "Broadway Frequent", 
              "90": "Woodlawn", 
              "93": "IH10 / UTSA Express", 
              "95": "Fredericksburg Road Frequent", 
              "96": "Vance Jackson Frequent", 
              "97": "West Avenue", 
              "999": "Encino Courtesy Van"}